### ISSUE TITLE
Keyboard support for (⌘+Z, ⌘+Y, etc)

### ISSUE THREAD

**Issue by joaocunha** [ArthurClemens/Javascript-Undo-Manager#13]
`⌘`+`Z` for undo, `⌘`+`shift`+`Z` and `⌘`+`Y` for redo, or even a custom combination.

Is this something you would pursue or would you rather leave it to the dev to implement?

**Comment by ArthurClemens** [comment]
It is application specific behaviour, and not desirable for all projects. So indeed I would leave this to individual devs.
