### ISSUE TITLE
add undo/redo pair at separate times.

### ISSUE THREAD

**Issue by rads17** [ArthurClemens/Javascript-Undo-Manager#14]
HI im trying to use undoManager to undo movement of an element, I have a function for when movement begins and when movement ends respectively. So I have written this:

```
                   dragstart: function (layer) {
                    // code to run when dragging starts
                        var dragstartx = layer.x;
                        var dragstarty = layer.y;
                        $canvas.undoManager.add({
                            undo:function(){
                                $canvas.setLayer(layer, {
                                    x:dragstartx,
                                    y:dragstarty
                                }).drawLayers();               
                            }
                        });


                    },
                    dragstop: function (layer){
                    // code to run when dragging starts
                        var dragstopx = layer.x;
                        var dragstopy = layer.y;
                        $canvas.undoManager.add({
                            redo:function(){
                                $canvas.setLayer(layer, {
                                    x:dragstopx,
                                    y:dragstopy
                                }).drawLayers();

                            }
                        });

                    },
```

This works *almost* perfect, the only issue is when you move twice and want to undo both, you have to actually hit redo 4 times because it seems to "insert" empty undo's whenever the dragstop adds the redo without specifying an undo.

**Comment by ArthurClemens** [comment]
If you want to go back to the point where the drag was initiated, and UndoManager expects an undo/redo pair, you can store the initial coordinates someplace, and use them at the end of the drag. Have a look at this example: http://jsbin.com/tidibi/edit?js,output

**Comment by rads17** [comment]
Alright so I had initial done a similiar thing to what you suggested, but it only worked for 1 drag, not undoing 2 drags, so then I thought well wouldn't it be easier to split it up and push the redo/undo separately, which IMHO I still think that would be a better design, BUT after reading you're code I figured out why it was only working for 1 drag.

You did this:
```
var dragStartX = obj.dragStartX;  <---- THIS LINE
 var dragStartY = obj.dragStartY;  <--- AND THIS LINE
 var x = obj.x;
  var y = obj.y;
```
Where as I was just using the stored value on the obj itself not saving again that value, so thank you for that.
