### ISSUE TITLE
Updating undo manager commands

### ISSUE THREAD

**Issue by Sharath-GitBan** [ArthurClemens/Javascript-Undo-Manager#20]
Hi,

I am using undo manager for an app where I can draw svg elements like (rect, circle, text, ellipse).
When I create a single rect element it calls multiple create/update methods and I am adding commands in this method, which results in adding lot of undo and redo calls for a single element.
Can you pls let me know is it possible to update the undo manager to keep only one command for each svg element created.

Thanks

**Comment by ArthurClemens** [comment]
Is it hard to tell what's not working. Do you have a code example?
