### ISSUE TITLE
can't install on Windows because of symlink in the 'postinstall' script

### ISSUE THREAD

**Issue by hlwz5735** [ArthurClemens/JavaScript-Undo-Manager#26]
On Mac or Linux systems, the 'postinstall' script which is 'sh scripts/link-lib.sh' works well.

But on Windows, you know, it can't read the 'sh' script. There is also no 'symbol link' on Windows's file system.

When you install this package by using 'npm install' or 'yarn install' on Windows, there will be some error output like this:
![image](https://github.com/ArthurClemens/JavaScript-Undo-Manager/assets/12751178/2eb34146-4956-418f-80c5-8fdbabf21b85)

So I just rollback to version 1.0.5 and lock the version in package.json.

**Comment by ArthurClemens** [comment]
Solved in release 1.1.1
